let g:go_fmt_fail_silently = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
nmap <buffer> <leader>r <Plug>(go-run-tab)
nmap <buffer> <leader>b <Plug>(go-build)
nmap <buffer> <leader>t <Plug>(go-test)
nmap <buffer> <Leader>d <Plug>(go-doc-browser)
let g:go_bin_path = expand('~/Programs/Go')
