#this assumes git and yaourt already installed 
# packages.txt generated by packup
# install packages
for x in $(cat packages.txt); do pacman -S $x;
# make backup directory for neovim
mkdir ~/.config/nvim/backup 
# install vimplug 
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
done;
